version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file: .env.dev
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - locotoko
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file: .env.test
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - locotoko
  prod-db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file: .env.prod
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

    networks:
      - locotoko
  server:
    image: locotoko:0.1.7
    ports:
      - 80:3333
    networks:
      - locotoko
networks:
  locotoko:
