services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    networks:
      - locotoko
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    networks:
      - locotoko
  prod-db:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - .env.prod
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - type: bind
        source: /data01/Store
        target: /var/lib/postgresql/data
    networks:
      - locotoko
  server:
    image: edsalisbury/locotoko:latest
    ports:
      - 80:3333
    environment:
      NODE_ENV: production
    networks:
      - locotoko
    env_file: .env.prod
  # Development container
  locotoko-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: locotoko-dev             # Use your custom dev image
    container_name: locotoko-dev
    working_dir: /usr/src/app
    command: tail -f /dev/null      # Keep the container running idle
    volumes:
      - locotoko-code:/usr/src/app       # Persistent volume for code
      - locotoko-node_modules:/node_modules   # Separate volume for node_modules
    ports:
      - "3333:3333"
      - "8080:8080"
    environment:
      NODE_ENV: development
    networks:
      - locotoko
  ebay:
    image: edsalisbury/locotoko:latest
    working_dir: /app/ebay
    command: node index.js
    env_file: .env.prod
networks:
  locotoko:

volumes:
  locotoko-code:         # Persistent volume for syncing code
  locotoko-node_modules: